apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:601311288054:certificate/5e6d905c-3ccb-4840-90e3-d745b6ded132
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/load-balancer-attributes: deletion_protection.enabled=false
    alb.ingress.kubernetes.io/load-balancer-name: pre-prod-tevico-cluster-alb
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/target-type: ip
  labels:
    app: lightmetrics
    component: ingress
    env: preprod
    id: 68278db6-4fcb-4b04-b71e-869e3872ceed
    owner: aafaq
    partner: lightmetrics
  name: lightmetrics
  namespace: tevico
spec:
  ingressClassName: alb-common
  rules:
  - host: lightmetrics.preprod.tevi.co
    http:
      paths:
      - backend:
          service:
            name: webapp
            port:
              number: 80
        path: /
        pathType: Prefix
